services:
  train:
    build:
      context: .
      dockerfile: Dockerfile.training
    volumes:
      - ./mlruns:/app/mlruns
      - ./data:/app/data
      - ./ml:/app/ml
      - ./ml/model:/app/model
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    command: python ml/model_training.py

  mlflow-ui:
    image: ghcr.io/mlflow/mlflow:v2.22.0
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow ui --backend-store-uri file:/mlflow/mlruns --host 0.0.0.0

  api:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8001:8001"
    depends_on:
      train:
        condition: service_completed_successfully

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app/dashboard
      - ./data:/app/data
    environment:
      - API_URL=http://api:8001/predict
    depends_on:
      api:
        condition: service_started